spring:
  application:
    name: bulletinexam
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/dbdocker
    password: bimilbunho7!
    username: chadocker
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 80